language: node_js
node_js:
- lts/*
branches:
  only:
  - master
cache:
  apt: true
  yarn: true
  directories:
  - node_modules
install:
- yarn
script:
- yarn build:dev
- sh ./deploy.sh
before_install:
- openssl aes-256-cbc -K $encrypted_31539db9e051_key -iv $encrypted_31539db9e051_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
